INSERT INTO disciplinas (nome, carga_horaria) VALUES
-- 1º Semestre
('Matemática Discreta', 80),
('Fundamentos de Sistemas de Informação', 60),
('Fundamentos de Sistemas Operacionais', 60),
('Linguagens Formais', 80),
('Programação Estruturada', 80),
('Inglês Instrumental', 40),

-- 2º Semestre
('Estatística Aplicada a Informática', 60),
('Análise Orientada à Objetos', 80),
('Modelagem de Dados', 60),
('Estrutura de Dados, Pesquisa e Ordenação', 80),
('Programação Web', 80),

-- 3º Semestre
('Fundamentos de Engenharia de Software', 60),
('Programação Orientada a Objetos I', 80),
('Banco de Dados I', 80),
('Análise e Projeto de Algoritmos', 80),
('Microcontroladores e Microprocessadores', 80),
('Inovação Tecnológica e Empreendedorismo', 80),

-- 4º Semestre
('Programação Orientada a Objetos II', 80),
('Análise e Projeto de Software', 80),
('Banco de Dados II', 80),
('Sistemas Multirobóticos', 60),
('Projeto Integrado I', 80),

-- 5º Semestre
('Processos de Desenvolvimento de Software', 80),
('Arquitetura de Software', 60),
('Gerência de Projetos', 80),
('Robótica Móvel', 60),
('Cultura, Sociedade e Tecnologia', 60),
('Fundamentos de Redes de Computadores', 80),

-- 6º Semestre
('Fundamentos de Sistemas Embarcados', 60),
('Gestão de Infraestrutura de Redes', 60),
('Governança de TIC', 80),
('Programação Mobile', 60),
('Compiladores e Interpretadores', 80),
('Projeto Integrado II', 80),

-- 7º Semestre
('Projeto de Redes e Segurança', 80),
('Estimativa de Software', 80),
('Realidade Virtual', 60),
('Interação Humano Computador', 80),
('Optativa I', 80),

-- 8º Semestre
('Design de Produtos Interativos Com Internet das Coisas', 40),
('Teste de Software', 80),
('Análise e Visualização de Dados', 80),
('Mineração de Dados', 80),
('Optativa II', 80),
('Trabalho de Conclusão de Curso', 80);

INSERT INTO disciplinas (nome, carga_horaria) VALUES
-- 1º Semestre
('Química Geral', 80),
('Introdução a Engenharia de Produção', 60),
('Desenho Técnico I', 80),
('Português Instrumental', 60),
('Geometria Analítica e Álgebra Linear', 80),
('Introdução a Cálculo para Engenharia', 60),
('Métodos Computacionais para Engenharia', 80),

-- 2º Semestre
('Atividade de Formação Complementar I', 40),
('Física Geral e Experimental I', 80),
('Química Experimental', 80),
('Gestão e Organização Empresarial', 80),
('Desenho Técnico II', 60),
('Estatística e Probabilidade para Engenharia I', 80),
('Cálculo Diferencial e Integral I', 80),
('Psicologia e Relações Humanas', 80),

-- 3º Semestre
('Física Geral e Experimental II', 80),
('Práticas de Pesquisa Científica em Eng. de Produção', 60),
('Mecânica Aplicada', 80),
('Gerenciamento da Produção', 80),
('Introdução à Ciência dos Materiais', 80),
('Cálculo Numérico', 80),
('Cálculo Diferencial e Integral II', 80),
('Estatística e Probabilidade para Engenharia II', 80),

-- 4º Semestre
('Atividade de Formação Complementar II', 40),
('Física Geral e Experimental III', 80),
('Economia da Empresa', 80),
('Engenharia de Métodos', 80),
('Fenômenos de Transporte', 120),
('Resistência dos Materiais', 80),
('Cálculo Diferencial e Integral III', 80),

-- 5º Semestre
('Física Geral e Experimental IV', 80),
('Análise de Demandas Regionais', 60),
('Engenharia Econômica I', 80),
('Metodologia de Elaboração de Projetos Científicos', 60),
('Planejamento e Controle da Produção I', 80),
('Higiene e Segurança do Trabalho', 80),
('Pesquisa Operacional I', 80),
('Ergonomia Aplicada', 80),

-- 6º Semestre
('Atividade de Formação Complementar III', 40),
('Gestão de Custos I', 80),
('Gestão de Projetos', 80),
('Gerência da Qualidade', 80),
('Planejamento e Controle da Produção II', 80),
('Energia e Projetos Elétricos', 80),
('Pesquisa Operacional II', 80),
('Engenharia do Produto e do Processo', 80),

-- 7º Semestre
('Organização do Trabalho', 60),
('Análise e Gestão Econômica de Projetos', 80),
('Engenharia e Gestão do Conhecimento', 80),
('Marketing', 80),
('Gestão e Sustentabilidade', 80),
('Projeto de Instalações', 60),
('Introdução a Automação Industrial', 80),
('Modelagem e Simulação de Sistemas de Produção', 80),

-- 8º Semestre
('Atividades de Formação Complementar IV', 20),
('Gerência de Materiais', 80),
('Empreendedorismo', 60),
('Legislação Social', 60),
('Gestão de Custos II', 80),
('Gerenciamento Ambiental na Indústria', 80),
('Tecnologia e Sistemas de Informação', 80),
('Logística e Supply Chain', 80),

-- 9º Semestre
('Consumo e Produção Sustentável', 60),
('Gestão de Pessoas e de Conflitos', 80),
('Projeto de TCC em Engenharia de Produção', 80),
('Controle Estatístico do Processo', 60),
('Gerência de Operações em Serviços', 60),
('Engenharia de Manutenção', 60),
('Processo e Gestão da Inovação', 60),

-- 10º Semestre
('Ética e Deontologia', 60),
('Trabalho de Conclusão de Curso (TCC)', 80),
('Estágio Supervisionado', 240);


INSERT INTO disciplinas (nome, carga_horaria) VALUES
-- BLOCO 1
('Introdução ao Cálculo para Engenharia', 60),
('Português Instrumental', 40),
('Química Geral', 60),
('Álgebra Linear e Geometria Analítica', 60),
('Métodos Computacionais para Engenharia', 60),
('Introdução à Engenharia Ambiental e Sanitária', 60),
('Sociologia e Meio Ambiente', 40),

-- BLOCO 2
('Cálculo Diferencial e Integral I', 60),
('Ecologia Aplicada à Engenharia', 60),
('Expressão Gráfica I', 60),
('Química Experimental', 60),
('Biologia e Microbiologia Ambiental', 60),
('Saúde e Meio Ambiente', 60),
('Cartografia e Topografia', 80),

-- BLOCO 3
('Cálculo Diferencial e Integral II', 60),
('Física Geral e Experimental I', 60),
('Expressão Gráfica II', 80),
('Ciências e Tecnologia dos Materiais', 60),
('Trabalhos Técnicos e Científicos em Eng. Ambiental e Sanitária', 40),
('Ecossistemas Aquáticos', 60),
('Mecânica Aplicada', 60),

-- BLOCO 4
('Cálculo Diferencial e Integral III', 60),
('Fenômenos do Transporte', 80),
('Física Geral e Experimental II', 60),
('Geologia', 60),
('Qualidade da Água', 80),
('Estatística Geral', 60),

-- BLOCO 5
('Física Geral e Experimental III', 60),
('Cálculo Numérico', 60),
('Hidráulica I', 80),
('Qualidade de Solo', 80),
('Resistência dos Materiais', 60),
('Gestão de Resíduos Sólidos', 60),
('Climatologia e Meteorologia', 60),

-- BLOCO 6
('Hidrologia', 60),
('Controle de Poluição Atmosférica', 80),
('Elementos de Projeto Estrutural', 60),
('Sistemas de Abastecimento de Água', 80),
('Hidráulica II', 60),
('Ecologia de Ecossistemas Amazônicos', 60),
('Fontes e Controle de Poluição Mineral', 60),

-- BLOCO 7
('Sistema de Informações Ambientais', 60),
('Avaliação de Impactos Ambientais I', 60),
('Gestão Ambiental e Legislação Aplicada', 80),
('Tratamento de águas Residuárias e Industriais', 80),
('Sistema de Esgotamento Sanitário', 40),
('Sistemas Elétricos', 60);

INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 4, id, 1 FROM disciplinas WHERE nome IN ('Matemática Discreta', 'Fundamentos de Sistemas de Informação', 'Fundamentos de Sistemas Operacionais', 'Linguagens Formais', 'Programação Estruturada', 'Inglês Instrumental');

INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 4, id, 2 FROM disciplinas WHERE nome IN ('Estatística Aplicada a Informática', 'Análise Orientada à Objetos', 'Modelagem de Dados', 'Estrutura de Dados, Pesquisa e Ordenação', 'Programação Web');

INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 4, id, 3 FROM disciplinas WHERE nome IN ('Fundamentos de Engenharia de Software', 'Programação Orientada a Objetos I', 'Banco de Dados I', 'Análise e Projeto de Algoritmos', 'Microcontroladores e Microprocessadores', 'Inovação Tecnológica e Empreendedorismo');

INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 4, id, 4 FROM disciplinas WHERE nome IN ('Programação Orientada a Objetos II', 'Análise e Projeto de Software', 'Banco de Dados II', 'Sistemas Multirobóticos', 'Projeto Integrado I');

INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 4, id, 5 FROM disciplinas WHERE nome IN ('Processos de Desenvolvimento de Software', 'Arquitetura de Software', 'Gerência de Projetos', 'Robótica Móvel', 'Cultura, Sociedade e Tecnologia', 'Fundamentos de Redes de Computadores');

INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 4, id, 6 FROM disciplinas WHERE nome IN ('Fundamentos de Sistemas Embarcados', 'Gestão de Infraestrutura de Redes', 'Governança de TIC', 'Programação Mobile', 'Compiladores e Interpretadores', 'Projeto Integrado II');

INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 4, id, 7 FROM disciplinas WHERE nome IN ('Projeto de Redes e Segurança', 'Estimativa de Software', 'Realidade Virtual', 'Interação Humano Computador', 'Optativa I');

INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 4, id, 8 FROM disciplinas WHERE nome IN ('Design de Produtos Interativos Com Internet das Coisas', 'Teste de Software', 'Análise e Visualização de Dados', 'Mineração de Dados', 'Optativa II', 'Trabalho de Conclusão de Curso');

-- 1º Semestre
INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 2, id, 1 FROM disciplinas WHERE nome IN ('Química Geral', 'Introdução a Engenharia de Produção', 'Desenho Técnico I', 'Português Instrumental', 'Geometria Analítica e Álgebra Linear', 'Introdução a Cálculo para Engenharia', 'Métodos Computacionais para Engenharia');

-- 2º Semestre
INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 2, id, 2 FROM disciplinas WHERE nome IN ('Atividade de Formação Complementar I', 'Física Geral e Experimental I', 'Química Experimental', 'Gestão e Organização Empresarial', 'Desenho Técnico II', 'Estatística e Probabilidade para Engenharia I', 'Cálculo Diferencial e Integral I', 'Psicologia e Relações Humanas');

-- 3º Semestre
INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 2, id, 3 FROM disciplinas WHERE nome IN ('Física Geral e Experimental II', 'Práticas de Pesquisa Científica em Eng. de Produção', 'Mecânica Aplicada', 'Gerenciamento da Produção', 'Introdução à Ciência dos Materiais', 'Cálculo Numérico', 'Cálculo Diferencial e Integral II', 'Estatística e Probabilidade para Engenharia II');

-- 4º Semestre
INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 2, id, 4 FROM disciplinas WHERE nome IN ('Atividade de Formação Complementar II', 'Física Geral e Experimental III', 'Economia da Empresa', 'Engenharia de Métodos', 'Fenômenos de Transporte', 'Resistência dos Materiais', 'Cálculo Diferencial e Integral III');

-- 5º Semestre
INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 2, id, 5 FROM disciplinas WHERE nome IN ('Física Geral e Experimental IV', 'Análise de Demandas Regionais', 'Engenharia Econômica I', 'Metodologia de Elaboração de Projetos Científicos', 'Planejamento e Controle da Produção I', 'Higiene e Segurança do Trabalho', 'Pesquisa Operacional I', 'Ergonomia Aplicada');

-- 6º Semestre
INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 2, id, 6 FROM disciplinas WHERE nome IN ('Atividade de Formação Complementar III', 'Gestão de Custos I', 'Gestão de Projetos', 'Gerência da Qualidade', 'Planejamento e Controle da Produção II', 'Energia e Projetos Elétricos', 'Pesquisa Operacional II', 'Engenharia do Produto e do Processo');

-- 7º Semestre
INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 2, id, 7 FROM disciplinas WHERE nome IN ('Organização do Trabalho', 'Análise e Gestão Econômica de Projetos', 'Engenharia e Gestão do Conhecimento', 'Marketing', 'Gestão e Sustentabilidade', 'Projeto de Instalações', 'Introdução a Automação Industrial', 'Modelagem e Simulação de Sistemas de Produção');

-- 8º Semestre
INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 2, id, 8 FROM disciplinas WHERE nome IN ('Atividades de Formação Complementar IV', 'Gerência de Materiais', 'Empreendedorismo', 'Legislação Social', 'Gestão de Custos II', 'Gerenciamento Ambiental na Indústria', 'Tecnologia e Sistemas de Informação', 'Logística e Supply Chain');

-- 9º Semestre
INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 2, id, 9 FROM disciplinas WHERE nome IN ('Consumo e Produção Sustentável', 'Gestão de Pessoas e de Conflitos', 'Projeto de TCC em Engenharia de Produção', 'Controle Estatístico do Processo', 'Gerência de Operações em Serviços', 'Engenharia de Manutenção', 'Processo e Gestão da Inovação');

-- 10º Semestre
INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 2, id, 10 FROM disciplinas WHERE nome IN ('Ética e Deontologia', 'Trabalho de Conclusão de Curso (TCC)', 'Estágio Supervisionado');

-- BLOCO 1
INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 3, id, 1 FROM disciplinas WHERE nome IN ('Introdução ao Cálculo para Engenharia', 'Português Instrumental', 'Química Geral', 'Álgebra Linear e Geometria Analítica', 'Métodos Computacionais para Engenharia', 'Introdução à Engenharia Ambiental e Sanitária', 'Sociologia e Meio Ambiente');

-- BLOCO 2
INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 3, id, 2 FROM disciplinas WHERE nome IN ('Cálculo Diferencial e Integral I', 'Ecologia Aplicada à Engenharia', 'Expressão Gráfica I', 'Química Experimental', 'Biologia e Microbiologia Ambiental', 'Saúde e Meio Ambiente', 'Cartografia e Topografia');

-- BLOCO 3
INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 3, id, 3 FROM disciplinas WHERE nome IN ('Cálculo Diferencial e Integral II', 'Física Geral e Experimental I', 'Expressão Gráfica II', 'Ciências e Tecnologia dos Materiais', 'Trabalhos Técnicos e Científicos em Eng. Ambiental e Sanitária', 'Ecossistemas Aquáticos', 'Mecânica Aplicada');

-- BLOCO 4
INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 3, id, 4 FROM disciplinas WHERE nome IN ('Cálculo Diferencial e Integral III', 'Fenômenos do Transporte', 'Física Geral e Experimental II', 'Geologia', 'Qualidade da Água', 'Estatística Geral');

-- BLOCO 5
INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 3, id, 5 FROM disciplinas WHERE nome IN ('Física Geral e Experimental III', 'Cálculo Numérico', 'Hidráulica I', 'Qualidade de Solo', 'Resistência dos Materiais', 'Gestão de Resíduos Sólidos', 'Climatologia e Meteorologia');

INSERT INTO disciplinas (nome, carga_horaria) VALUES
-- 1º Semestre
('Introdução ao Cálculo Diferencial e Integral', 45),
('Introdução a Engenharia Florestal', 30),
('Morfologia e Anatomia Vegetal', 60),
('Computação aplicada a Engenharia Florestal', 30),
('Bioquímica vegetal', 60),
('Química Geral', 60),
('Leitura e Produção de Textos Acadêmicos', 30),
('Introdução em Ambientes Virtuais de Aprendizagem', 30),
('Microbiologia Geral', 60),

-- 2º Semestre
('Cálculo Diferencial e Integral I', 60),
('Física Geral I', 60),
('Botânica e Sistemática Florestal', 60),
('Estatística', 60),
('Química Analítica', 60),
('Metodologia Científica e Tecnológica', 45),
('Ecologia e Sustentabilidade', 30),
('Química Experimental', 30),
('Expressão Gráfica', 45),

-- 3º Semestre
('Cálculo Diferencial e Integral II', 60),
('Física Geral II', 60),
('Genética Básica', 45),
('Climatologia e Meteorologia', 60),
('Ecologia Florestal', 60),
('Fisiologia Vegetal', 60),
('Programação aplicada a Engenharia Florestal', 45),
('Gênese, Morfologia e Classificação de solos', 60),
('Desenho Universal', 45),

-- 4º Semestre
('Química da Madeira', 60),
('Anatomia da Madeira', 60),
('Entomologia Florestal', 60),
('Fitopatologia Florestal', 60),
('Fenômenos de Transporte', 60),
('Eletricidade Aplicada', 60),
('Química e Fertilidade do Solo', 45),
('Biologia, Produção e Tecnologia de Sementes Florestais', 60),

-- 5º Semestre
('Viveiros Florestais', 45),
('Propriedades Físicas e Mecânicas da Madeira', 60),
('Dendrologia', 60),
('Topografia', 60),
('Estudo de Impactos Ambientais', 60),
('Introdução a Administração e Economia', 45),
('Biodegradação e Preservação da Madeira', 45),
('Fundamentos da Ciência dos Materiais', 60),
('Física do Solo', 45);

-- 1º Semestre
INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 1, id, 1 FROM disciplinas WHERE nome IN ('Introdução ao Cálculo Diferencial e Integral', 'Introdução a Engenharia Florestal', 'Morfologia e Anatomia Vegetal', 'Computação aplicada a Engenharia Florestal', 'Bioquímica vegetal', 'Química Geral', 'Leitura e Produção de Textos Acadêmicos', 'Introdução em Ambientes Virtuais de Aprendizagem', 'Microbiologia Geral');

-- 2º Semestre
INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 1, id, 2 FROM disciplinas WHERE nome IN ('Cálculo Diferencial e Integral I', 'Física Geral I', 'Botânica e Sistemática Florestal', 'Estatística', 'Química Analítica', 'Metodologia Científica e Tecnológica', 'Ecologia e Sustentabilidade', 'Química Experimental', 'Expressão Gráfica');

-- 3º Semestre
INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 1, id, 3 FROM disciplinas WHERE nome IN ('Cálculo Diferencial e Integral II', 'Física Geral II', 'Genética Básica', 'Climatologia e Meteorologia', 'Ecologia Florestal', 'Fisiologia Vegetal', 'Programação aplicada a Engenharia Florestal', 'Gênese, Morfologia e Classificação de solos', 'Desenho Universal');

-- 4º Semestre
INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 1, id, 4 FROM disciplinas WHERE nome IN ('Química da Madeira', 'Anatomia da Madeira', 'Entomologia Florestal', 'Fitopatologia Florestal', 'Fenômenos de Transporte', 'Eletricidade Aplicada', 'Química e Fertilidade do Solo', 'Biologia, Produção e Tecnologia de Sementes Florestais');

-- 5º Semestre
INSERT INTO curso_disciplinas (curso_id, disciplina_id, semestre_disciplina)
SELECT 1, id, 5 FROM disciplinas WHERE nome IN ('Viveiros Florestais', 'Propriedades Físicas e Mecânicas da Madeira', 'Dendrologia', 'Topografia', 'Estudo de Impactos Ambientais', 'Introdução a Administração e Economia', 'Biodegradação e Preservação da Madeira', 'Fundamentos da Ciência dos Materiais', 'Física do Solo');

INSERT INTO disciplinas (nome, carga_horaria) VALUES
-- 1º Semestre
('Introdução à Física', 80),
('Vetores e Geometria Analítica', 60),
('Tópicos de Matemática Aplicada a Física I', 80),
('Produção de Gêneros Acadêmicos', 80),
('Psicologia da Educação', 80),
('Tecnologias da informação e comunicação aplicadas ao ensino de Física', 80),
('Metodologia Científica', 80),

-- 2º Semestre
('Tópicos de Física I', 80),
('Tópicos de Matemática Aplicada a Física II', 80),
('Estatística Aplicada', 60),
('Epistemologia e História da Ciência I', 80),
('Didática Geral e Especial', 80),
('Teoria e Prática de Ensino de Física I', 80),
('Políticas Públicas e Educação', 80),

-- 3º Semestre
('Tópicos de Física II', 80),
('Métodos Matemáticos da Física Teórica I', 80),
('Laboratório de Física I', 40),
('Fundamentos Teóricos e Metodológicos da Educação Especial', 80),
('Introdução à Astronomia', 80),
('Teoria e Prática de Ensino de Física II', 80),
('Fundamentos Teóricos e Metodológicos da Educação de jovens e adultos', 80),

-- 4º Semestre
('Tópicos de Física III', 100),
('Sociologia da Educação', 80),
('Laboratório de Física II', 40),
('Princípios da Mecânica Clássica', 80),
('Filosofia da Educação', 80),
('Teoria e Prática de Ensino de Física III', 80),
('Gestão Educacional', 80),

-- 5º Semestre
('Tópicos de Física IV', 100),
('Termodinâmica e Introdução a Física Estatística', 80),
('Métodos Matemáticos da Física Teórica II', 80),
('Laboratório de Física III', 40),
('Estágio supervisionado I: aspectos gerais da realidade escolar', 120),
('Teoria e Prática de Ensino de Física IV', 80);

INSERT INTO disciplinas (nome, carga_horaria) VALUES
-- 1º Semestre
('Cálculo diferencial e integral', 60),
('Química geral e inorgânica', 60),
('Biologia celular', 60),
('Português instrumental', 60),
('Introdução à tecnologia de alimentos', 60),
('Ética e deontologia', 30),

-- 2º Semestre
('Probabilidade e estatística', 60),
('Química orgânica', 60),
('Bioquímica de alimentos', 60),
('Física aplicada à tecnologia de alimentos', 60),
('Microbiologia geral', 60),
('Metodologia do trabalho científico', 60),

-- 3º Semestre
('Microbiologia de alimentos', 60),
('Química analítica', 60),
('Fisico-química', 60),
('Princípios de nutrição', 45),
('Higiene e legislação de alimentos', 60),
('Análise sensorial', 60),

-- 4º Semestre
('Análise de alimentos', 90),
('Fenômenos de transporte', 60),
('Operações unitárias na indústria de alimentos I', 60),
('Tecnologia de produtos de origem vegetal I', 60),
('Tecnologia de produtos de origem animal I', 60),
('Embalagens de alimentos', 45),

-- 5º Semestre
('Operações unitárias na indústria de alimentos II', 60),
('Tecnologia de produtos de origem vegetal II', 60),
('Tecnologia de produtos de origem animal II', 60),
('Engenharia de processos na indústria de alimentos', 60),
('Controle de qualidade na indústria de alimentos', 60),
('Gestão ambiental e tratamento de resíduos', 60);